[binding] add new api and refine codes
wenet-e2e/wespeaker pull request #136
Opened 2023-02-26 09:07 UTC by cdliang11

1. Add new api:

    - compute_cosine_score
    - extract_embedding_feat

2. Rename `Inference` to `Speaker`.

2023-02-26 11:51 UTC, robin1001 commented on runtime/binding/python/py/inference.py
>  import kaldiio
rename the file to speaker.py

2023-02-26 12:03 UTC, robin1001 commented on runtime/binding/python/py/inference.py
>      def extract_embedding(self,
This is the most important interface. I think we should keep it for extracting embedding and return numpy ndarrary, which is preferred for most users.

And we can add something like `extract_embedding_kaldi`, in which the input and output are in kaldi style(scp/ark)

2023-02-26 12:08 UTC, robin1001 commented on runtime/binding/python/README.md
> +### Extract embedding from feature(fbank)
The readme should be refactored if `extract_embedding` is kept as ndarray interface.

Here is the recommended order the outline.
1.  Extract speaker embedding
2.  Compute speaker simliarity
3.  Optional, Extract speaker embedding with fbank feature
4. Optional, Extract speaker embedding with kaldi IO

2023-02-26 12:08 UTC, robin1001 requested changes
please see inline.

2023-02-26 17:10 UTC, cdliang11 commented
> please see inline.

done.

2023-02-27 01:13 UTC, robin1001 approved these changes

2023-02-27 01:14 UTC, robin1001 commented
Great job!

2023-02-27 01:14 UTC, robin1001 commented
Great job!

2023-02-27 01:14 UTC, merged

2023-02-27 02:41 UTC, cdliang11 commented
Uploaded to [pypi](https://pypi.org/project/wespeakerruntime/), and the [huggingface demo](https://huggingface.co/spaces/wenet/wespeaker_demo) has been updated.